### PR TITLE
Added Chronos support for date and Datetime

### PR DESCRIPTION
**Pull request by mvrhov**
This is just a preliminary.

As the Chronos comes with Date only class I'd like to separate timestamps from date only. WDYT?

### CODE REVIEW

**Comment by chanmix51** [comment]
This would create a dependency to cakePHP & Chronos in Foundation. Why not create a separate plugin? The change that may be needed in Foundation would be how to easily integrate such plugin. 

💡 maybe the method that would add them to the converter holder could be added with a trait and called in the project’s `SessionBuilder` class.

**Comment by mvrhov** [comment]
The dependency is optional. You have to explicitly say that you want to use the Chronos instead of DateTime

**Comment by chanmix51** [comment]
Good. But still, like the Linux kernel comes bare with its compiled modules as an extra package, like PostgreSQL comes with a contrib package for extensions, I think it would be good to propose an extra plugin to Foundation that would add such optional features.

The question is: what would be the best name for such package?

**Comment by mvrhov** [comment]
So what would be your suggestion. I'd need this in my next project. But I really cannot afford 2+ days of development.

**Comment by chanmix51** [comment]
Right, can you send me a tar with the files so I create a `ChronosExtension` project? Do not forget to mention your name (and contact) as class author 😃

**Comment by mvrhov** [comment]
@chanmix51 Do I understand correctly you want me to extract the "diff" to another directory and send you the result?
Do you plan to create a new extension project for each extension... Then maybe it would be better if all of them would reside in a one repo pomm-extensions or similar. This would be then similar to twig and doctrine extensions repositories.

**Comment by chanmix51** [comment]
true 👍 One extension to rule them all!

**Comment by chanmix51** [comment]
okay, I think we can close this one. It is always possible to propose a plugin to add those extra converters to Pomm (whatever the vendor).

**Comment by mvrhov** [comment]
WEll in such case you should at least respond to an email message

**Pull request closed without merging**
