### PR TITLE
PHP 8.1

### LINKED ISSUE #125: PgSql Result error on php 8.1
On construction of ResultHandler wrapper class the result must be a resource of type 'pgsql result' but, in php 8.1, the pgresult resource is replace by `PgSql\Result` class and cause an InvalidArgumentException `"Given handler is not a resource of a pgsql result nor a PgSql\Result ('object' given)."`.

### PR DESCRIPTION
**Pull request by arno09**
closes #125

### CODE REVIEW

**Comment by chanmix51** [comment]
thank you

**Comment by arno09** [comment]
You're welcome.
Have you planned to tag this version to avoid depending on dev-master ?

**Comment by chanmix51** [comment]
That's a lot of work to release a version (starting by setting up a new CI), probably not before 2022.

**Comment by arno09** [comment]
ok, thanks !

**Comment by dougetovski** [comment]
Hi,
I'm not sure to understand the need of setting a new CI. The actual one isn't good enough ? Also, the new code pushed by @arno09 doesn't seem to be bcb, but i could be wrong.

**Pull request merged**
