### PR TITLE
Persistent connections

### PR DESCRIPTION
**Pull request by DrunkPyromaniac**
Add in a new configuration option to allow persistent connections (through using `pg_pconnect()`).

### CODE REVIEW

**Comment by DrunkPyromaniac** [comment]
I know that this is an option that should be used with great care - and indicated so in the documentation.

**Comment by chanmix51** [comment]
Thank you for your PR. For me to know, what problem are you solving with this?

**Comment by DrunkPyromaniac** [comment]
We have the one real use case where persistent connections actually help.  We have one web server serving many internal clients, and most of our requests are very short-lived.  This will eliminate the connection set-up and tear-down overhead.

**Comment by chanmix51** [comment]
Be aware connections are explicitly closed when the Session instances are destroyed (see [this code](https://github.com/pomm-project/Foundation/blob/master/sources/lib/Session/Session.php#L106)).

**Comment by DrunkPyromaniac** [comment]
Calling `pg_close()` on a connection opened with `pg_pconnect()` just releases it back into the connection pool that PHP uses.

**Comment by chanmix51** [comment]
thank you

**Comment by chanmix51** [comment]
May we have a feedback on the performance improvement this PR provided?

**Pull request merged**
