### PR TITLE
Fix PgJson::fromPg throws exception for a boolean false literal

### PR DESCRIPTION
**Pull request by tlode**
PgJson converter wasn't able to convert from a simple `false` literal due to a false return value check.

Also the converter exception message was a bit unclear. It returned the integer value of json_last_error() without giving the right context.

To perform the atoum tests with php 7 I had to update atoum to the latest dev-master version

### CODE REVIEW

**Comment by chanmix51** [comment]
We need to drop support for PHP 5.5…

**Comment by chanmix51** [comment]
We are working on Atoum to set a working version with PHP 5.5

**Comment by chanmix51** [comment]
Now, I tested more about the special case you are addressing. 

```SQL
(9.5.6/postgres) postgres=$ select 'true'::json;
┌──────┐
│ json │
├──────┤
│ true │
└──────┘
(1 row)

(9.5.6/postgres) postgres=$ select '6'::json;
┌──────┐
│ json │
├──────┤
│ 6    │
└──────┘
(1 row)

(9.5.6/postgres) postgres=$ select 'whatever'::json;
ERROR:  invalid input syntax for type json
LINE 1: select 'whatever'::json;
               ^
DETAIL:  Token "whatever" is invalid.
CONTEXT:  JSON data, line 1: whatever

(9.5.6/postgres) postgres=$ select true::json;
ERROR:  cannot cast type boolean to json
LINE 1: select true::json;
                   ^
```
This means we have to convert integers as well (see [this part of the RFC](https://tools.ietf.org/html/rfc7159#section-3)) As far as I could read, strings should be supported as well, it seems Pg9.5 does not comply with this RFC (2014). We have to check this against Pg 9.6.

This said, be aware that:

```SQL
(9.5.6/postgres) postgres=# select 'true'::json = true;
ERROR:  operator does not exist: json = boolean
LINE 1: select 'true'::json = true;
                            ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```
Which means `true` as JSON is *not* considered as a simple boolean value. 

Does this distinction make sense in PHP ?

**Comment by tlode** [comment]
These are json type primitives and php `json_decode` does support these as well as postgres

```php
var_dump(json_decode('6')); // int(6)
var_dump(json_decode('6.2')); // double(6.2)
var_dump(json_decode('"watever"')); // string(7) "watever"
var_dump(json_decode(null)); // NULL
var_dump(json_decode('null')); // NULL
var_dump(json_decode('true')); // bool(true)
var_dump(json_decode('false')); //bool(false)
```

```sql
# select '"whatever"'::json;
    json
------------
 "whatever"
(1 row)
```

**Comment by chanmix51** [comment]
:+1: , our converter must be able to convert them as well… I will checkout your PR in a branch.

**Pull request merged**
