### PR TITLE
Fixing french sentences translated a bit too literally (first pass)

### PR DESCRIPTION
**Pull request by gnugat**
* replacing "propose" with "provide"
* the verb "do" is usually used to emphasis a point

### CODE REVIEW

**Comment by chanmix51** [comment]
Thank you :heavy_exclamation_mark:

**Comment by gnugat** [comment]
Also I've spotted the use of "overload" and "override": I'm not sure which one is correct (I've also heard about "overwrite"), but it'd be nice to pick one and stick to it. What do you think?

**Comment by chanmix51** [comment]
Oh well, the only occurrence of `override` is when you can overload a method to override configuration defaults value … (could not find `overwrite`). From my point of view:

 * methods are overloaded
 * configuration settings are overridden 
 * files are overwritten 

This said, you are right because I could find several occurrences of `overload` for classes and classes are extended. I fix these.

**Comment by gnugat** [comment]
Thanks for the explanation, I often ask myself "which one should I use" when writing documentation :)

**Pull request merged**
